sudo: required
services:
    - docker
language: generic

before_install:
    - docker build -t antonio/docker-react-test -f Dockerfile.dev .

script:
    - docker run antonio/docker-react-test npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-test"
    env: "DockerReactTest-env"
    bucket_name: "elasticbeanstalk-us-east-2-774948942702"
    bucket_path: "docker-react-test"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY