sudo: required
services:
    - docker
language: generic

before_install:
    - docker build -t antonio/docker-react-test -f Dockerfile.dev .

script:
    - docker run antonio/docker-react-test npm run test -- --coverage